# Generated by Django 4.2.4 on 2023-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_hotel_room_specialreservation_regularreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
