# Generated by Django 4.2.4 on 2023-10-29 19:06

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()

    for p in persons:
        if p.age <= 12:
            p.age_group = 'Child'
        elif p.age <= 17:
            p.age_group = 'Teen'
        else:
            p.age_group = 'Adult'

    person_model.objects.bulk_update(persons, ['age_group'])

def reverse_set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    persons = person_model.objects.all()

    person_age_group_default = person_model._meta.get_field('age_group').default

    for p in persons:
        p.age_group = person_age_group_default

    person_model.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=reverse_set_age_group)
    ]
