# Generated by Django 4.2.4 on 2023-10-29 19:42

from django.db import migrations


def set_rarity_by_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for i in items:
        if i.price <= 10:
            i.rarity = 'Rare'
        elif i.price <= 20:
            i.rarity = 'Very Rare'
        elif i.price <= 30:
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items, ['rarity'])


def reverse_set_rarity_by_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    default_rarity = item_model._meta.get_field('rarity').default

    for i in items:
        i.rarity = default_rarity

    item_model.objects.bulk_update(items, ['rarity'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity_by_price, reverse_code=reverse_set_rarity_by_price)
    ]
