# Generated by Django 4.2.4 on 2023-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_exercise_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
