# Generated by Django 4.2.4 on 2023-10-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='range',
            new_name='age',
        ),
    ]
