# Generated by Django 4.2.4 on 2023-10-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
    ]
